Description of njGetTimes
njGetTimes
PURPOSE
njGetTimes Get entire time vector for variable 'var' from any CF-compliant
SYNOPSIS
function result=njGetTimes(netcdfDatasetObj,timeIndex)
DESCRIPTION
njGetTimes Get entire time vector for variable 'var' from any CF-compliant
file or just a single time specified by time index
CROSS-REFERENCE INFORMATION
This function calls:
end mGeoGridVar/end -- Evaluate "end" as an index. (overloaded method)
end mVar/end -- Evaluate "end" as an index. (overloaded method)
This function is called by:
getTimes mGridCoordinates/getTimes - Get time(s) in DATENUM format
getTimes mVar/getTimes - Get time(s) in DATENUM format