Description of njReadVariable
njReadVariable
PURPOSE
njReadVariable: Read data from variable
SYNOPSIS
function data=njReadVariable(varID,start, count, stride)
DESCRIPTION
 njReadVariable:  Read data from variable
 Usage:    u=njReadVariable(varID,start,count,stride);
   where:  varID = msstate.cstm.data.JVariable%
           start = A 1-based array specifying the position in the file to begin reading or corner of a
                   hyperslab e.g [1 2 1]. Specify 'inf' for last index.
                   The values specified must not exceed the size of any
                   dimension of the data set.
           count = A 1-based array specifying the length of each dimension to read. e.g [6 10 inf].
                   Specify 'inf' to get all the values from start index.
           stride = A 1-based array specifying the interval between the
                    values to read. e.g [1 2 2]
CROSS-REFERENCE INFORMATION
This function calls:
end mGeoGridVar/end -- Evaluate "end" as an index. (overloaded method)
end mVar/end -- Evaluate "end" as an index. (overloaded method)
parseINF Utilties/parseINF - Assign 'inf' the correct dimension value
This function is called by:
getData mVar/getData - Read data from variable.