Description of parseIndices
parseIndices
PURPOSE
mVariable/parseIndices - parses subscripting references into
SYNOPSIS
function [start count stride] = parseIndices(indices, varShape)
DESCRIPTION
mVariable/parseIndices - parses subscripting references into
 start,count and stride based on variable shape.
CROSS-REFERENCE INFORMATION
This function calls:
end mGeoGridVar/end -- Evaluate "end" as an index. (overloaded method)
end mVar/end -- Evaluate "end" as an index. (overloaded method)
This function is called by:
subsref mGeoGridVar/subsref -- Overloaded "{}", "()", and "." operators.
subsref mVar/subsref -- Overloaded "{}", "()", and "." operators.