Description of nj_setcache
nj_setcache
PURPOSE
NJ_SETCACHE - Enables caching for aggregating datasets
SYNOPSIS
function set=nj_setcache(cacheDir, persistMinutes, scourEveryMinutes)
DESCRIPTION
NJ_SETCACHE - Enables caching for aggregating datasets
 Usage:
   set=nj_setcache(cacheDir, persistMinutes, scourEveryMinutes);
 where,
   cacheDir - The full path name to the directory of the cache. Must be writeable.
   persistMinutes - how old a file should be before deleting.
   scourEveryMinutes - how often to run the scour process. If <= 0, don't scour.
 e.g.,
   Cache every hour and delete stuff older than 30 days.
   nj_setcache('/home/rsignell/nj_cache', 60*24*30, 60));
   nj_setcache('c:\rps\nj_cache', 60*24*30, 60));
Sachin Kumar Bhate (skbhate@ngi.msstate.edu) (c) 2008
Mississippi State University.
CROSS-REFERENCE INFORMATION
This function calls:
nj_setcache NJ_SETCACHE - Enables caching for aggregating datasets
end mGeoGridVar/end -- Evaluate "end" as an index. (overloaded method)
end mVar/end -- Evaluate "end" as an index. (overloaded method)
This function is called by:
nj_setcache NJ_SETCACHE - Enables caching for aggregating datasets